/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/client/branches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список филиалов
         * @description Возвращает список всех активных филиалов.
         */
        get: operations["DelivestWeb.Client.Branch.BranchController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/branches/{branch_id}/menu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить меню филиала
         * @description Возвращает список категорий с предзагруженными товарами для филиала из кеша или БД.
         */
        get: operations["DelivestWeb.Client.Menu.MenuController.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/client/branches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить филиал по ID
         * @description Возвращает детальную информацию о филиале с предзагруженными данными (info).
         */
        get: operations["DelivestWeb.Client.Branch.BranchController.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Branch */
        Branch: {
            branch_info?: components["schemas"]["BranchInfoResponse"] | null;
            /**
             * Format: uuid
             * @example c4a3b8e0-1234-5678-9abc-def012345678
             */
            id?: string;
            /** @example true */
            is_active?: boolean;
            /** @example Центральный филиал */
            name?: string;
            /** @example central */
            slug?: string;
        };
        /** BranchInfoResponse */
        BranchInfoResponse: {
            /** @example ул. Пушкина, д. 10 */
            address?: string | null;
            /**
             * Format: uuid
             * @example 8f3b2c10-91ab-4cd2-81e2-123456789abc
             */
            id?: string;
            /** @example https://instagram.com/profile_name */
            instagram_url?: string | null;
            /** @example +79990000000 */
            phone_number?: string | null;
            /** @example https://vk.com/group_name */
            vk_url?: string | null;
            /** @example https://wa.me/79990000000 */
            whatsapp_url?: string | null;
        };
        /** BranchListResponse */
        BranchListResponse: {
            data?: components["schemas"]["Branch"][];
        };
        /** BranchResponse */
        BranchResponse: {
            data?: components["schemas"]["Branch"];
        };
        /** CategoryResponse */
        CategoryResponse: {
            /**
             * Format: uuid
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            id?: string;
            /** @example true */
            is_active?: boolean;
            /** @example Пиццы */
            name?: string;
            /**
             * Format: float
             * @example 1
             */
            order?: number;
            products?: components["schemas"]["ProductResponse"][];
        };
        /** MenuResponse */
        MenuResponse: {
            data?: components["schemas"]["CategoryResponse"][];
        };
        /** ProductResponse */
        ProductResponse: {
            /** @example Сочная пицца с колбасками */
            description?: string;
            external_id?: string | null;
            /**
             * Format: uuid
             * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
             */
            id?: string;
            /** @example true */
            is_active?: boolean;
            /** Format: uuid */
            media_id?: string | null;
            /** @example Пипперони */
            name?: string;
            /**
             * @description Цена в копейках/минимальных единицах
             * @example 590
             */
            price?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "DelivestWeb.Client.Branch.BranchController.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список филиалов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchListResponse"];
                };
            };
            /** @description Ошибка получения списка */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Failed to fetch branches */
                        error?: string;
                    };
                };
            };
        };
    };
    "DelivestWeb.Client.Menu.MenuController.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description UUID филиала
                 * @example c4a3b8e0-1234-5678-9abc-def012345678
                 */
                branch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Меню филиала с категориями и товарами */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuResponse"];
                };
            };
            /** @description Ошибка получения меню */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Failed to fetch menu */
                        error?: string;
                    };
                };
            };
        };
    };
    "DelivestWeb.Client.Branch.BranchController.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description UUID филиала
                 * @example c4a3b8e0-1234-5678-9abc-def012345678
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Детальная информация о филиале */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BranchResponse"];
                };
            };
            /** @description Филиал не найден */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Branch not found */
                        error?: string;
                    };
                };
            };
        };
    };
}
